### ISSUE TITLE
Login support for users

### ISSUE THREAD

**Issue by RaoBhethanabotla** [saayam-for-all/webapp#6]
When users come to our main landing page, Saayam.org, on the top menu bar, far right, we should show a Login option. When users click on, we show the AWS Cognito login/register dialog. Refer to the New User Login use case in https://github.com/saayam-for-all/docs/wiki/Use-Cases.

**Comment by SasankTanikella99** [comment]
I will go through AWS cognito today, and I will refer the docs.

**Comment by SasankTanikella99** [comment]
I just visited docs and I am going through the documentation

**Comment by SasankTanikella99** [comment]
Hello Rao,
Just created a login page on Saayam, I created a new branch and pushed my changes to that branch.
