### ISSUE TITLE
Step 1 of Volunteering Promotion wizard - UI

### ISSUE THREAD

**Issue by RaoBhethanabotla** [saayam-for-all/webapp#78]
As the first step of the volunteering promotion wizard, we will ask users to read this doc and sign it officially. We need to record this event in our DB properly. Well, we are NOT using YET any official signing tools like DocuSign yet, but we will need to integrate with those soon.

We need to show a link to the PDF document and a checkbox for user to select as if he/she has read our PDF doc. When user clicks on the Next button, we need to persist this date and time as a proof.

**Comment by rajesh9442** [comment]
Can I get the link for pdf document.
